from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class UserProfile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  first_name = models.CharField(max_length=20)
  last_name = models.CharField(max_length=20)

class Contact(models.Model):
  first_name = models.CharField(max_length=20)
  last_name = models.CharField(max_length=20)
  email = models.EmailField(blank=True, null=True, max_length=254)
  address_1 = models.CharField(blank=True, null=True, max_length=20)
  address_2 = models.CharField(blank=True, null=True, max_length=20)
  city = models.CharField(blank=True, null=True, max_length=20)
  state = models.CharField(blank=True, null=True, max_length=20)
  zipcode = models.IntegerField(blank=True, null=True)
  profile_photo = models.ImageField(blank=True, null=True)
  user = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True)
  #foreign key requires on_delete in case relational table is deleted. setting it to null instead of cascade since contacts generated by a user should not be lost even if user no longer exist.

